import type { Metadata } from "next";
import "./globals.css";
import { Sofia_Sans } from "next/font/google";

// 1. Import your Navbar component
// Adjust the path based on where you saved it (e.g., ./components/Navbar)
import Navbar from "@/components/Navbar";

const sofiaPro = Sofia_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-sofia-pro",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sofiaPro.className} antialiased`}>
        {/* 2. Add the Navbar here */}
        <Navbar />

        {/* The main content of your pages will render below */}
        {children}
      </body>
    </html>
  );
}
